### ISSUE TITLE
Add find_packages option

### ISSUE THREAD

**Issue by jackmaney** [juanpabloaj/pip-init#1]
It would be nice to have an option for the user to just have `packages=setuptools.find_packages()` within `setup`. Maybe something like:

```
Would you like setuptools to find packages for you automatically? (Y/n)
```

If the user answers `Y`, he/she could then be prompted for:
- Whether or not they want to specify by excluding or including certain packages (`e/i/Neither`).
- Where they want to search for packages (relative to the local path) (default of `'.'`).

This should probably include a warning that it's best to specify includes and excludes via `MANIFEST.in`.

I've forked the repo, and I believe I could include this feature this weekend. Would a pull request be welcome?

**Comment by juanpabloaj** [comment]
hey @jackmaney !

I was thinking in this issue, what is the best way to add the `packages=` line in the `setup.py file` ? ...

A option, like you say, is use `find_packages()`. Other option, the package name as default package to add, like `packages=['package_name']` ...

about the pull request, yes every pull request is welcome ;)

**Comment by juanpabloaj** [comment]
maybe the first and more simple solution is add by default

```
packages=setuptools.find_packages()
```

without make a question, and in the next commits, decide the better way to make the question to the user.

**Comment by msabramo** [comment]
:+1: to starting with find_packages

When you make it configurable you might also offer the option to use `py_modules`.
