### ISSUE TITLE
Issues with parse_requirements 

### ISSUE THREAD

**Issue by eejiawen** [juanpabloaj/pip-init#18]
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\user>pip install spcchart
Downloading/unpacking spcchart
  Downloading spcchart-0.22.tar.gz
  Running setup.py (path:c:\users\user\appdata\local\temp\pip_build_user\spcchar
t\setup.py) egg_info for package spcchart
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "c:\users\user\appdata\local\temp\pip_build_user\spcchart\setup.py",
line 8, in <module>
        install_requires = [str(ir.req) for ir in install_reqs]
      File "C:\Python27\lib\site-packages\pip-7.0.3-py2.7.egg\pip\req\req_file.p
y", line 70, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'sessio
n'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "c:\users\user\appdata\local\temp\pip_build_user\spcchart\setup.py", line
 8, in <module>

```
install_requires = [str(ir.req) for ir in install_reqs]
```

  File "C:\Python27\lib\site-packages\pip-7.0.3-py2.7.egg\pip\req\req_file.py",
line 70, in parse_requirements

```
"parse_requirements() missing 1 required keyword argument: "
```

TypeError: parse_requirements() missing 1 required keyword argument: 'session'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in c:\users\user\appda
ta\local\temp\pip_build_user\spcchart
Storing debug log for failure in C:\Users\user\pip\pip.log

C:\Users\user>

I am having this issue when trying to install python package: spcchart.
Sincerely hope there will be someone can help me fix this problem.

**Comment by juanpabloaj** [comment]
...  but I'm not the maintainer of spcchart ... why you post a this issue here ?
