### ISSUE TITLE
if user don't use git, how generate author name? 

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/pip-init#4]
about the commit f40b5fda7a91349a8fed3146061b96c54ad1565e 

If the user don't use git or the user don't have the global configuration of git, how generate the user name ? 

@davidyen1124 some ideas ?

**Comment by msabramo** [comment]
I would suggest `getpass.getuser` as a fallback.

**Comment by juanpabloaj** [comment]
@msabramo thanks for your suggestion. yes, I was thinking in use `getpass.getuser`.

but first, is necessary catch the exception when the user does not use git or does not have the global configuration.

**Comment by msabramo** [comment]
I can't remember whether subprocess.communicate raises an exception or just sets a returncode

**Comment by juanpabloaj** [comment]
@davidyen1124 with your commit this issue is fixed, thanks.

and thanks @msabramo by your suggestion about `getpass.getuser`

with this changes, I upload the [version 0.0.6](https://pypi.python.org/pypi?:action=display&name=pip-init&version=0.0.6) to pypi :tada:
