### ISSUE TITLE
requirements not installed from requirements.txt

### ISSUE THREAD

**Issue by juanpabloaj** [juanpabloaj/pip-init#6]
If I try

``` bash
$ pip-init
name (package-name): dump-package
version (0.1.0):
description (A pip package):
license (MIT):
author (JuanPablo):
$ echo requests > requirements.txt
$ python setup.py sdist build
$ cd dist
$ pip install dump-package-0.1.0.tar.gz
```

this command installs `dump-package`, but not installs the dependency `requests`.

**Comment by msabramo** [comment]
I wouldn't expect that to work. `requirements.txt` is different from `install_requires` in setup.py. 

https://caremad.io/2013/07/setup-vs-requirement/

**Comment by juanpabloaj** [comment]
in @f4e44a7aa7670b8fdd37cb5f9bd66d5e1cec23cf set default value of `install_requires` to `[]`
